### ISSUE TITLE
[BUG] Config files are all empty.

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#7] opened 2024-09-27 21:07 UTC
For some unknown reason, the dll file produces empty config files, now the game is back to vanilla.

- Mod: 1.2.3
- Game: 1.4.2

**Additional context**

**Comment by xamionex** [comment] 2024-09-27 22:00
Can you reproduce this and when does it happen?

**Comment by xamionex** [comment] 2024-09-27 22:05
Fixed in 5c8432c

**Comment by user7562** [comment] 2024-09-27 22:42
> Should be fixed in [5c8432c](https://github.com/xamionex/DarkwoodCustomizer/commit/5c8432cb2ceff6f55e244306da03eeb3ca137767) Reply if issue is fixed

issue is not fixed at all, heres my outputlog:

[Message:   BepInEx] BepInEx 5.4.23.2 - Darkwood (9/17/2024 5:43:32 PM)
[Info   :   BepInEx] Running under Unity v2021.3.30.11810317
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [DarkwoodCustomizer 1.2.3]
[Info   :   BepInEx] Loading [Runtime Unity Editor 5.4.1]
[Message:   BepInEx] Chainloader startup complete
[Info   :Runtime Unity Editor] Successfully initialized 14/14 features: CursorUnlocker, WireframeFeature, ContextMenu, Taskbar, MouseInspect, ReplWindow, ObjectViewWindow, ProfilerWindow, ObjectTreeViewer, Inspector, ClipboardWindow, ChangeHistoryWindow, DnSpyHelper, GizmoDrawer

**Comment by xamionex** [comment] 2024-09-27 22:43
That log states it's still loading 1.2.3, are you sure you replaced the old version with 1.2.4

**Comment by xamionex** [comment] 2024-09-27 22:43
You can always get the latest here: https://github.com/xamionex/DarkwoodCustomizer/archive/refs/heads/main.zip
(DarkwoodCustomizer.dll)

**Comment by user7562** [comment] 2024-09-27 22:46
> That log states it's still loading 1.2.3, are you sure you replaced the old version with 1.2.4

i just installed the newest version and apparently it registers it as 1.2.3

**Comment by xamionex** [comment] 2024-09-27 22:50
> > That log states it's still loading 1.2.3, are you sure you replaced the old version with 1.2.4
> 
> i just installed the newest version and apparently it registers it as 1.2.3

Can you test this version out?
[DarkwoodCustomizer.zip](https://github.com/user-attachments/files/17171155/DarkwoodCustomizer.zip)

**Comment by user7562** [comment] 2024-09-27 22:54
> > i just installed the newest version and apparently it registers it as 1.2.3
> 
> Can you test this version out? [DarkwoodCustomizer.zip](https://github.com/user-attachments/files/17171155/DarkwoodCustomizer.zip)

yes this works, although the stacks dont work properly, only the wood and nails are affected, what is the default folder even for?

**Comment by xamionex** [comment] 2024-09-27 22:58
> yes this works, although the stacks dont work properly, only the wood and nails are affected, what is the default folder even for?

The default folder is just to see the default custom jsons assigned by me, by default you know
since the customx.json is dynamic and a config file, new values I assign to it will not be added to the config, only on errors or when getting made for the first time

Also nothing about stack sizes was changed and I just tested it and it works, stack sizes require save reload so maybe you thought it wasn't working

**Comment by user7562** [comment] 2024-09-27 23:00
> > yes this works, although the stacks dont work properly, only the wood and nails are affected, what is the default folder even for?
> 
> The default folder is just to see the default custom jsons assigned by me, by default you know since the customx.json is dynamic and a config file, new values I assign to it will not be added to the config, only on errors or when getting made for the first time
> 
> Also nothing about stack sizes was changed and I just tested it and it works, stack sizes require save reload so maybe you thought it wasn't working

my bad on my end, i was looking at the old config folders. do i delete the old stack and character config folders?

**Comment by user7562** [comment] 2024-09-27 23:03
also what does 1.0 damage mean? does that mean the target is gonna deal 1 point of damage?

**Comment by xamionex** [comment] 2024-09-27 23:04
> my bad on my end, i was looking at the old config folders. do i delete the old stack and character config folders?

I'm not sure how your config folder looks for you but this is how it should look (Ignore UnityRuntimeEditor):
![image](https://github.com/user-attachments/assets/1ce72cff-6392-4a8e-a957-d815c71153ac)
![image](https://github.com/user-attachments/assets/124eb938-1055-4667-8a7f-436fb8d69c43)

**Comment by user7562** [comment] 2024-09-27 23:06
> > my bad on my end, i was looking at the old config folders. do i delete the old stack and character config folders?
> 
> I'm not sure how your config folder looks for you but this is how it should look (Ignore UnityRuntimeEditor): ![image](https://private-user-images.githubusercontent.com/57235791/371706570-1ce72cff-6392-4a8e-a957-d815c71153ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Nzg1NjcsIm5iZiI6MTcyNzQ3ODI2NywicGF0aCI6Ii81NzIzNTc5MS8zNzE3MDY1NzAtMWNlNzJjZmYtNjM5Mi00YThlLWE5NTctZDgxNWM3MTE1M2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDIzMDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlY2E5MzkyOTE4MWRiNDU2MDRiODg2MzZlZjFkNmMxYTFiNGUxMDA5YjJmYTk3OTk0ZDc0NjQwMjE5NjQ5NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0nYgzdziZIp23U1q_4brZXnJuhtPnEkNBmAb4MUC2Qg) ![image](https://private-user-images.githubusercontent.com/57235791/371706590-124eb938-1055-4667-8a7f-436fb8d69c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Nzg1NjcsIm5iZiI6MTcyNzQ3ODI2NywicGF0aCI6Ii81NzIzNTc5MS8zNzE3MDY1OTAtMTI0ZWI5MzgtMTA1NS00NjY3LThhN2YtNDM2ZmI4ZDY5YzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDIzMDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMjYxMzUwNGRjMDM3ZmZjNDNiNGFiMDU5MDEzZWFlNmY4NTg5MjFmZWEzMzc3MWQyMTMxZmJmYTg4MmNiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m9Yf4rFh18lUWH1GAi37fCHPlGmosDPVzJ1ggRJLLWo)

mine looks like that as well, its just im confused which cfg do i use for stacks and characters. do i use Stacks.cfg? or CustomStacks.json. do i use Characters.cfg? or CustomCharacters.json?

**Comment by xamionex** [comment] 2024-09-27 23:08
Both, .cfg files are for enabling them
Jsons are for editing custom characters

Btw read Logging.cfg under [Note]
what you are looking at are probably old configs I have moved to be saved differently

**Comment by user7562** [comment] 2024-09-27 23:10
> Both, .cfg files are for enabling them Jsons are for editing custom characters
> 
> Btw read Logging.cfg under [Note] what you are looking at are probably old configs I have moved to be saved differently (you are safe to delete these)

i tested it and CustomStacks.json works ingame instead of Stacks.cfg. so im using the jsons

**Comment by xamionex** [comment] 2024-09-27 23:12
> i tested it and CustomStacks.json works ingame instead of Stacks.cfg. so im using the jsons
Going to close this issue now
Do read the note in Logging.cfg
Have fun ;P

**Closed by xamionex** 2024-09-27 23:12 UTC
Labels: bug

**Comment by user7562** [comment] 2024-09-27 23:15
> also what does 1.0 damage mean? does that mean the target is gonna deal 1 point of damage?

alright, can you elaborate on this real quick?

**Comment by xamionex** [comment] 2024-09-27 23:18
> > also what does 1.0 damage mean? does that mean the target is gonna deal 1 point of damage?
> 
> alright, can you elaborate on this real quick?

It means they're gonna deal attack damage * 1.0
No other way I could've implemented this without spending much more time on it

**Comment by user7562** [comment] 2024-09-27 23:19
> > > also what does 1.0 damage mean? does that mean the target is gonna deal 1 point of damage?
> > 
> > 
> > alright, can you elaborate on this real quick?
> 
> It means they're gonna deal attack damage * 1.0 No other way I could've implemented this without spending much more time on it

so 1.0 means 1 damage or 10 damage?

**Comment by xamionex** [comment] 2024-09-27 23:23
> so 1.0 means 1 damage or 10 damage?

Each enemy has a set of attacks
Instead of modifying every attack type for that enemy, you are simply taking them all and multiplying them by the damage value you assign
So if a dog deals 10 damage and you set it's damage in the json to be 0.5 it's gonna deal 5 damage

**Comment by user7562** [comment] 2024-09-27 23:26
> > so 1.0 means 1 damage or 10 damage?
> 
> Each enemy has a set of attacks Instead of modifying every attack type for that enemy, you are simply taking them all and multiplying them by the damage value you assign So if a dog deals 10 damage and you set it's damage in the json to be 0.5 it's gonna deal 5 damage

what if i wanna make a npc deal above 100 damage? how would that look like in the config?

**Comment by xamionex** [comment] 2024-09-27 23:30
> what if i wanna make a npc deal above 100 damage? how would that look like in the config?

100 is the default player's healthbar amount
I'll be adding attack type damage logging to the console soon
But honestly I'm not sure
Maybe 3 or 4? A dog deals like half a pip of damage in the base game so multiplying that by 2 it'll deal almost 1 pip and by 3x it's gonna deal 1.5 pips and 4 it's gonna deal 2 full pips

**Comment by user7562** [comment] 2024-09-27 23:35
> > what if i wanna make a npc deal above 100 damage? how would that look like in the config?
> 
> 100 is the default player's healthbar amount I'll be adding attack type damage logging to the console soon But honestly I'm not sure Maybe 3 or 4? A dog deals like half a pip of damage in the base game so multiplying that by 2 it'll deal almost 1 pip and by 3x it's gonna deal 1.5 pips and 4 it's gonna deal 2 full pips

alright so, that will be 1.00 damage?

**Comment by xamionex** [comment] 2024-09-27 23:37
> alright so, that will be 1.00 damage?

It's literally just a multiplier for the enemy's damage, if you set it to 4x it's gonna deal 4x as much damage 
For a dog 100dmg would be 4.0

**Comment by user7562** [comment] 2024-09-27 23:42
> > alright so, that will be 1.00 damage?
> 
> It's literally just a multiplier for the enemy's damage, if you set it to 4x it's gonna deal 4x as much damage For a dog 100dmg would be 4.0

is this applied to health and speed as well? or only for damage

**Comment by xamionex** [comment] 2024-09-27 23:43
> is this applied to health and speed as well? or only for damage

Only for damage

**Comment by user7562** [comment] 2024-09-27 23:46
> > is this applied to health and speed as well? or only for damage
> 
> Only for damage

alright got it, will you make the damage direct? so no multipliers any of that? just raw damage

**Comment by xamionex** [comment] 2024-09-27 23:48
> > > is this applied to health and speed as well? or only for damage
> > 
> > Only for damage
> 
> alright got it, will you make the damage direct? so no multipliers any of that? just raw damage

Every enemy has its own list of attacks it can do, probably but later, I wanna rest for a bit xd

**Comment by user7562** [comment] 2024-09-27 23:52
> > > > is this applied to health and speed as well? or only for damage
> > > 
> > > 
> > > Only for damage
> > 
> > 
> > alright got it, will you make the damage direct? so no multipliers any of that? just raw damage
> 
> Every enemy has its own list of attacks it can do, probably but later, I wanna rest for a bit xd

understandable, and thanks. normally devs just ignore my bug reports or requests so its literally a godsend for a cooperative dev like this to meet.
